CREATE TABLE users (id uuid PRIMARY KEY, identity text UNIQUE NOT NULL, name text NOT NULL, avatar text);
CREATE TABLE auth_sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users, expires_at timestamptz NOT NULL);
CREATE TABLE workspaces (id uuid PRIMARY KEY, name text NOT NULL, owner_id uuid NOT NULL REFERENCES users);
CREATE TABLE memberships (workspace_id uuid REFERENCES workspaces, user_id uuid REFERENCES users, PRIMARY KEY (workspace_id,user_id));
CREATE TABLE invites (id uuid PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces, token_hash text UNIQUE NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz);
CREATE TABLE channels (id uuid PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces, name text NOT NULL, UNIQUE(workspace_id,name));
CREATE TABLE topics (id uuid PRIMARY KEY, channel_id uuid NOT NULL REFERENCES channels, title text NOT NULL, next_seq integer NOT NULL DEFAULT 0, activity_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE messages (id uuid PRIMARY KEY, topic_id uuid NOT NULL REFERENCES topics, seq integer NOT NULL, author_type text NOT NULL CHECK(author_type IN ('human','bot','system')), author_id uuid NOT NULL, author_name text NOT NULL, body text NOT NULL, human_only boolean NOT NULL DEFAULT false, client_key uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(topic_id,seq), UNIQUE(topic_id,author_id,client_key));
CREATE TABLE mentions (message_id uuid REFERENCES messages, target_type text NOT NULL CHECK(target_type IN ('human','bot')), target_id uuid NOT NULL, PRIMARY KEY(message_id,target_type,target_id));
CREATE TABLE attachments (id uuid PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces, owner_id uuid NOT NULL REFERENCES users, topic_id uuid NOT NULL REFERENCES topics, message_id uuid REFERENCES messages, object_key text UNIQUE NOT NULL, name text NOT NULL, media_type text NOT NULL, size integer NOT NULL CHECK(size>0), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE read_cursors (user_id uuid REFERENCES users, topic_id uuid REFERENCES topics, seq integer NOT NULL DEFAULT 0, PRIMARY KEY(user_id,topic_id));
CREATE TABLE pairings (token_hash text PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces, owner_id uuid NOT NULL REFERENCES users, expires_at timestamptz NOT NULL, consumed_at timestamptz);
CREATE TABLE hosts (id uuid PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces, owner_id uuid NOT NULL REFERENCES users, name text NOT NULL, token_hash text UNIQUE NOT NULL, version text NOT NULL, last_seen timestamptz, revoked_at timestamptz, setup_error text);
CREATE TABLE projects (id uuid PRIMARY KEY, host_id uuid NOT NULL REFERENCES hosts, local_id uuid NOT NULL, label text NOT NULL, available boolean NOT NULL, UNIQUE(host_id,local_id));
CREATE TABLE bots (id uuid PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces, owner_id uuid NOT NULL REFERENCES users, host_id uuid NOT NULL REFERENCES hosts, default_project_id uuid NOT NULL REFERENCES projects, name text NOT NULL, handle text NOT NULL, shared boolean NOT NULL DEFAULT false, enabled boolean NOT NULL DEFAULT true, UNIQUE(workspace_id,handle));
CREATE TABLE bot_projects (bot_id uuid REFERENCES bots, project_id uuid REFERENCES projects, PRIMARY KEY(bot_id,project_id));
CREATE TABLE bindings (id uuid PRIMARY KEY, topic_id uuid NOT NULL REFERENCES topics, bot_id uuid NOT NULL REFERENCES bots, generation integer NOT NULL DEFAULT 1, epoch integer NOT NULL DEFAULT 1, participation text NOT NULL DEFAULT 'following' CHECK(participation IN ('following','dismissed')), UNIQUE(topic_id,bot_id));
CREATE TABLE agent_sessions (id uuid PRIMARY KEY, binding_id uuid NOT NULL REFERENCES bindings, generation integer NOT NULL, host_id uuid NOT NULL REFERENCES hosts, project_id uuid NOT NULL REFERENCES projects, thread_id text, cursor integer NOT NULL DEFAULT 0, start_seq integer NOT NULL DEFAULT 0, state text NOT NULL DEFAULT 'following', error text, UNIQUE(binding_id,generation));
CREATE TABLE requests (id uuid PRIMARY KEY, session_id uuid NOT NULL REFERENCES agent_sessions, message_id uuid NOT NULL REFERENCES messages, epoch integer NOT NULL, state text NOT NULL CHECK(state IN ('pending','dispatched','accepted','completed','canceled','offline','uncertain','failed')), due_at timestamptz NOT NULL, UNIQUE(session_id,message_id));
CREATE TABLE runs (id uuid PRIMARY KEY, session_id uuid NOT NULL REFERENCES agent_sessions, epoch integer NOT NULL, status text NOT NULL CHECK(status IN ('dispatching','accepted','working','completed','failed','interrupted','uncertain','stopping')), context jsonb NOT NULL, thread_id text, turn_id text, error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX one_run_per_session ON runs(session_id) WHERE status IN ('dispatching','accepted','working','stopping');
CREATE TABLE run_requests (run_id uuid REFERENCES runs, request_id uuid REFERENCES requests, PRIMARY KEY(run_id,request_id));
CREATE TABLE host_events (host_id uuid REFERENCES hosts, event_id uuid NOT NULL, PRIMARY KEY(host_id,event_id));
CREATE TABLE output_items (run_id uuid REFERENCES runs, item_id text NOT NULL, PRIMARY KEY(run_id,item_id));
CREATE TABLE attachment_grants (token_hash text PRIMARY KEY, attachment_id uuid NOT NULL REFERENCES attachments, session_id uuid NOT NULL REFERENCES agent_sessions, run_id uuid NOT NULL REFERENCES runs, expires_at timestamptz NOT NULL);
CREATE TABLE events (id bigserial PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces, kind text NOT NULL, topic_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX events_workspace ON events(workspace_id,id);
CREATE INDEX pending_requests ON requests(session_id,due_at) WHERE state='pending';
CREATE INDEX messages_topic ON messages(topic_id,seq DESC);
CREATE INDEX attachments_message ON attachments(message_id);
CREATE INDEX members_user ON memberships(user_id);
